---
# This role install all the flask runtime environmnet 
# I used NGINX to proxy the client requests
# - eloy.acosta@gmail.com

- name: Install base packages  
  apt: name={{ item }} state=present
  with_items:
   - python 
   - python-pip
   - python-virtualenv
   - nginx
   - gunicorn
   - supervisor 

##- name: Install Pytest
 # pip: name=flask

- name: Install Python modules
  pip: name={{ item }} state=present
  with_items:
  - pymongo
  - python-dateutil
  - unittest2

- name: Install Flask 
  pip: name=flask
  notify: activate python virtualenv

- name: Create environment directory 
  file: path=/home/www/ state=directory

# I use a template to provide the IP address NGINX should listen
- name: Configure NGINX 
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  # I want NGINX to be reloaded if the config file changes 
  notify: reload NGINX

- name: Ensure NGINX is started 
  service: name=nginx state=started enabled=yes

- name: Configure supervisor to run Gunicorn
  copy: src=myapp.conf dest=/etc/supervisor/conf.d/
  # I want my app to be reloaded if anything changes 
  notify: restart flask app

- name: Ensure supervisor is started 
  service: name=supervisor state=started enabled=yes
